# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoName', models.CharField(max_length=50, verbose_name='姓名')),
                ('ceoDesc', models.CharField(max_length=255, verbose_name='话录')),
                ('ceoJob', models.CharField(max_length=100, verbose_name='职务')),
                ('ceoImg', models.ImageField(upload_to='', verbose_name='照片')),
            ],
            options={
                'verbose_name_plural': '领导层寄语',
                'verbose_name': '领导层寄语',
            },
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseClassifield', models.CharField(max_length=50, verbose_name='课程方向')),
                ('courseName', models.CharField(max_length=50, verbose_name='课程名称')),
            ],
            options={
                'verbose_name_plural': '课程分类',
                'verbose_name': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('studentStudy', models.CharField(max_length=50, verbose_name='所学课程')),
                ('studentDesc', models.CharField(max_length=255, verbose_name='毕业后情况')),
                ('studentImg', models.ImageField(upload_to='', verbose_name='照片')),
            ],
            options={
                'verbose_name_plural': '学生表',
                'verbose_name': '学生表',
            },
        ),
        migrations.CreateModel(
            name='StudyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyName', models.CharField(max_length=50, verbose_name='课程名称')),
                ('studyCourse', models.CharField(max_length=50, verbose_name='总课时')),
                ('studyTime', models.CharField(max_length=255, verbose_name='学习时长')),
                ('studyCounts', models.CharField(max_length=100, verbose_name='正在学习的人数')),
            ],
            options={
                'verbose_name_plural': '课程表',
                'verbose_name': '课程表',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachName', models.CharField(max_length=50, verbose_name='老师姓名')),
                ('teachCourse', models.CharField(max_length=50, verbose_name='讲授课程')),
                ('teachDesc', models.CharField(max_length=255, verbose_name='话录')),
                ('teachBigPic', models.ImageField(upload_to='', verbose_name='大照片')),
                ('teachSmallPic', models.ImageField(upload_to='', verbose_name='小照片')),
            ],
            options={
                'verbose_name_plural': '教师表',
                'verbose_name': '教师表',
            },
        ),
    ]
