# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maizi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentSay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='语录 '),
        ),
    ]
