# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-05 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maizi_app', '0002_students_studentsay'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylist',
            name='studyImg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='课程图标'),
        ),
    ]
